title: Evidence Synthesis Hackathon
author: Martin Westgate & Neal Haddaway
description: An event series to develop open software for evidence synthesis
theme: minima
show_excerpts: true
twitter_username: eshackathon
github_username: ESHackathon
email: eshackathon@gmail.com
google_analytics: UA-121833450-3
header_pages:
- events/2019-04-canberra.md
- event_list.md