title: Evidence Synthesis Hackathon
author: Martin Westgate & Neal Haddaway
description: An event series to develop open software for evidence synthesis
theme: minima
github_username: ESHackathon
email: eshackathon@gmail.com
header_pages:
- pages/events/2019_04_canberra/home.md
- pages/event_list.md
- pages/events/2019_04_canberra/organizers.md