title: Evidence Synthesis Hackathon
author: Martin Westgate & Neal Haddaway
description: An event series to develop open software for evidence synthesis
theme: minima
show_excerpts: true
twitter_username: eshackathon
github_username: ESHackathon
email: eshackathon@gmail.com
google_analytics: UA-121833450-3
collections_dir: collections
collections:
  about:
    output: true
  discussions:
    output: true
  events:
    output: true
  people:
    output: true
  posts:
    output: true
  software:
    output: true
header_pages:
  - about.md
  - events.md
  - people.md
  - projects.md